#!/bin/bash

find . -name '*.php' -exec dos2unix {} \;
find . -name '*.xml' -exec dos2unix {} \;

version=$(grep '<version>' mod_bis.xml | sed -e 's/<[a-z\/]*>//g' | sed -e 's/ *//g')

zip -r module_bis-${version}-j3X.zip tmpl js css helper.php cs-CZ.* en-GB.*  mod_bis.php mod_bis.xml index.html
